/** Default example state loaded on first launch when no saved data exists. */
export const DEFAULT_STATE = JSON.stringify({
  userSettings: {},
  workspaces: {
    ws_example: {
      id: "ws_example",
      name: "Example",
      createdAt: 1774171132968,
      updatedAt: 1774195723651,
    },
  },
  activeWorkspaceId: null,
  trash: [],
  elements: {
    el_ex_note: {
      id: "el_ex_note",
      type: "note",
      parentBoardId: "ws_example",
      position: { x: 180, y: 160 },
      content: "Welcome to Umbra!\nDouble-click the canvas to create more notes.",
      width: 260,
      height: 120,
      color: "blue",
      createdAt: 1774195120413,
    },
    el_ex_board: {
      id: "el_ex_board",
      type: "board",
      parentBoardId: "ws_example",
      position: { x: 500, y: 160 },
      content: "My Board",
      width: 180,
      height: 100,
      createdAt: 1774195123809,
    },
    el_ex_checklist: {
      id: "el_ex_checklist",
      type: "checklist",
      parentBoardId: "ws_example",
      position: { x: 740, y: 160 },
      content: JSON.stringify([
        { id: "item_1", text: "Try dragging this card", done: false },
        { id: "item_2", text: "Click a tool to create", done: false },
        { id: "item_3", text: "Drag a tool onto the canvas", done: false },
      ]),
      width: 240,
      height: 200,
      createdAt: 1774195130658,
    },
    el_ex_text: {
      id: "el_ex_text",
      type: "text",
      parentBoardId: "ws_example",
      position: { x: 180, y: 340 },
      content: "Text Block",
      width: 240,
      height: 60,
      textFontSize: 32,
      createdAt: 1774195297926,
    },
    el_ex_table: {
      id: "el_ex_table",
      type: "table",
      parentBoardId: "ws_example",
      position: { x: 500, y: 340 },
      content: JSON.stringify({
        cells: [
          ["Name", "Role", "Status"],
          ["Alice", "Design", "Active"],
          ["Bob", "Dev", "Active"],
        ],
        cellStyles: {
          "0,0": { bold: true },
          "0,1": { bold: true },
          "0,2": { bold: true },
        },
      }),
      width: 360,
      height: 140,
      tableShadeFirstRow: true,
      tableShowTitle: true,
      tableTitle: "Team",
      createdAt: 1774195310732,
    },
    el_ex_arrow1: {
      id: "el_ex_arrow1",
      type: "arrow",
      parentBoardId: "ws_example",
      position: { x: 0, y: 0 },
      content: "",
      width: 0,
      height: 0,
      linkFromId: "el_ex_note",
      linkToId: "el_ex_board",
      linkFromSide: "right",
      linkToSide: "left",
      connectorMode: "straight",
      connectorColor: "#4a9eff",
      connectorThickness: 2.5,
      createdAt: 1774195511576,
    },
    el_ex_arrow2: {
      id: "el_ex_arrow2",
      type: "arrow",
      parentBoardId: "ws_example",
      position: { x: 0, y: 0 },
      content: "",
      width: 0,
      height: 0,
      linkFromId: "el_ex_checklist",
      linkToId: "el_ex_table",
      linkFromSide: "bottom",
      linkToSide: "right",
      connectorMode: "orthogonal",
      connectorColor: "#ffc44a",
      connectorThickness: 2.5,
      createdAt: 1774195546728,
    },
  },
});
